Subedits
rdarshan927/SLIITOpenSource pull request #2
Opened 2023-08-27 18:57 UTC by rdarshan927

just changed personal links to public
updated target in the right notice part
linked stylesheets ... no big deal in visibility except the contact page
just to notify

2023-08-27 18:59 UTC, rdarshan927 commented
and we'll think about the extra folder later ... it'll be there until then

2023-08-28 05:38 UTC, nmdra commented on main.css
Any Reason to adding h3 ?. I think it's unwanted for now. 
If you wanna add it, remove Line 34 (flex Order).

2023-08-28 05:41 UTC, nmdra submitted a review, later dismissed

2023-08-28 05:45 UTC, nmdra requested changes
File: main.css

Any Reason to adding h3 ?. I think it's unwanted for now.
If you wanna add it, remove Line 34 (flex Order).

2023-08-28 06:11 UTC, rdarshan927 commented
it was just the sketch to include, it's not the actual interface design to be included in the page!
(is it good to add the contribute button in contact or contributers page?)

2023-08-28 08:43 UTC, closed without merging